### PR TITLE
Port to Python3

### LINKED ISSUE #2: Port to Python 3
Activity Written in Python2 consider porting to Python3

### PR DESCRIPTION
**Pull request by ghost**
This Port to Python3 and also removed the warning of missing gtk module.
This closes https://github.com/sugarlabs/pyeyes-activity/issues/2

### CODE REVIEW

**Comment by ghost** [comment]
kindly review @walterbender @chimosky @quozl 
In the commit https://github.com/sugarlabs/pyeyes-activity/pull/3/commits/fd6660d0533fde57ca1a992698f2ec628e14f3c1 I tried with GDK int as it is suggested for python3 but it turns out to be bad so i reverted back to original code only.
Thankyou.

**Comment by quozl** [comment]
Reviewed.  Tested.  Emits an ERROR.

**Comment by ghost** [comment]
Screenshot 2024-03-23 at 2 48 14 AM
Is it not running or any specific error if you can mention because its working on my side except for bundle id which is not mentioned?

**Comment by ghost** [comment]
This version uses OpenCV 1.0.
The XO not have that library, and, in some cases (like in Uruguay), don't have root permissions.
For this cause, this activity include the library to don't depend of the root password to install it.
If this is related also I am unaware about how to change bundle_id if you can specify.
Thankyou.

**Comment by quozl** [comment]
Yes. the service_name property error occurs.  Please fix it.  The message explains how.

No, it doesn't use OpenCV.  That was removed in an earlier commit.

**Comment by ghost** [comment]
@quozl changed Thankyou!

**Pull request merged**
